import { DurableObject } from "cloudflare:workers";

const json=(d,s=200)=>Response.json(d,{status:s,headers:{"Cache-Control":"no-store"}});
const enc=new TextEncoder();
const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("");
async function hash(v){return hex(await crypto.subtle.digest("SHA-256",enc.encode(v)))}
async function phash(p,s=crypto.randomUUID()){const k=await crypto.subtle.importKey("raw",enc.encode(p),"PBKDF2",false,["deriveBits"]);const b=await crypto.subtle.deriveBits({name:"PBKDF2",salt:enc.encode(s),iterations:100000,hash:"SHA-256"},k,256);return s+":"+hex(b)}
async function pverify(p,x){const [s,e]=String(x||"").split(":");return!!s&&!!e&&(await phash(p,s)).split(":")[1]===e}
function cookie(n,v,a){return `${n}=${v}; Path=/; Max-Age=${a}; HttpOnly; Secure; SameSite=Lax`}
async function me(r,db){const m=r.headers.get("Cookie")?.match(/(?:^|; )sc_session=([^;]+)/);if(!m)return null;return db.prepare("SELECT u.id,u.username,u.email,u.display_name FROM auth_users u JOIN sessions s ON s.user_id=u.id WHERE s.token_hash=? AND s.expires_at>datetime('now') AND u.email_verified=1").bind(await hash(m[1])).first()}
async function init(db){await db.batch([
 db.prepare(`CREATE TABLE IF NOT EXISTS auth_users(id TEXT PRIMARY KEY,username TEXT UNIQUE NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,email_verified INTEGER NOT NULL DEFAULT 0,display_name TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`),
 db.prepare(`CREATE TABLE IF NOT EXISTS email_otps(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,otp_hash TEXT NOT NULL,expires_at TEXT NOT NULL,attempts INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`),
 db.prepare(`CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,token_hash TEXT UNIQUE NOT NULL,expires_at TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`),
 db.prepare(`CREATE TABLE IF NOT EXISTS app_posts(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,username TEXT NOT NULL,content TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`),
 db.prepare(`CREATE TABLE IF NOT EXISTS friend_requests(id TEXT PRIMARY KEY,sender_id TEXT NOT NULL,receiver_id TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(sender_id,receiver_id))`),
 db.prepare(`CREATE TABLE IF NOT EXISTS friendships(id TEXT PRIMARY KEY,user1_id TEXT NOT NULL,user2_id TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(user1_id,user2_id))`),
 db.prepare(`CREATE TABLE IF NOT EXISTS chat_keys(user_id TEXT PRIMARY KEY,public_key TEXT NOT NULL,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`)
])}
async function otpMail(env,email,otp){if(!env.RESEND_API_KEY)return false;const from=env.FROM_EMAIL||"Social Chat <onboarding@resend.dev>";const r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({from,to:[email],subject:"Social Chat Gmail verification",html:`<h2>Your Social Chat OTP: ${otp}</h2><p>It expires in 10 minutes.</p>`})});return r.ok}
function pair(a,b){return a<b?[a,b]:[b,a]}
async function friendship(db,a,b){const p=pair(a,b);return !!(await db.prepare("SELECT id FROM friendships WHERE user1_id=? AND user2_id=?").bind(...p).first())}

export class ChatRoom extends DurableObject{
 async fetch(r){if(r.headers.get("Upgrade")?.toLowerCase()!=="websocket")return new Response("Expected WebSocket",{status:426});const u=new URL(r.url),username=(u.searchParams.get("username")||"User").slice(0,40);const [client,server]=Object.values(new WebSocketPair());this.ctx.acceptWebSocket(server);server.serializeAttachment({username});return new Response(null,{status:101,webSocket:client})}
 webSocketMessage(ws,msg){let p;try{p=JSON.parse(typeof msg==="string"?msg:"{}")}catch{return}if(p?.type!=="encrypted"||typeof p.senderPublicKey!=="string"||!Array.isArray(p.recipients))return;const s=ws.deserializeAttachment()||{};this.broadcast(JSON.stringify({type:"encrypted",user:s.username,senderPublicKey:p.senderPublicKey,recipients:p.recipients}))}
 webSocketClose(){} webSocketError(ws){try{ws.close()}catch{}}
 broadcast(m){for(const ws of this.ctx.getWebSockets())if(ws.readyState===WebSocket.OPEN)try{ws.send(m)}catch{}}
}

export default {async fetch(r,env){const url=new URL(r.url);await init(env.DB);
 if(url.pathname==="/home.html"){if(!await me(r,env.DB))return Response.redirect(new URL("/",r.url),302);return env.ASSETS.fetch(r)}
 if(url.pathname.startsWith("/chat/")){const u=await me(r,env.DB);if(!u)return new Response("Login required",{status:401});if(r.headers.get("Upgrade")?.toLowerCase()!=="websocket")return new Response("Expected WebSocket",{status:426});const name=decodeURIComponent(url.pathname.slice(6)),other=await env.DB.prepare("SELECT id,username FROM auth_users WHERE lower(username)=lower(?) AND email_verified=1").bind(name).first();if(!other||!(await friendship(env.DB,u.id,other.id)))return new Response("You can message only accepted friends",{status:403});const target=new URL(r.url);target.search=`?username=${encodeURIComponent(u.username)}&peer=${encodeURIComponent(other.username)}`;return env.CHAT_ROOM.get(env.CHAT_ROOM.idFromName(pair(u.username,other.username).join(":"))).fetch(new Request(target,r))}
 if(!url.pathname.startsWith("/api/"))return env.ASSETS.fetch(r);
 if(url.pathname==="/api/signup"&&r.method==="POST"){const b=await r.json().catch(()=>({})),username=String(b.username||"").trim(),email=String(b.email||"").trim().toLowerCase(),password=String(b.password||"");if(!/^[A-Za-z0-9_]{3,30}$/.test(username))return json({ok:false,error:"Username 3-30 characters: letters, numbers and _ only"},400);if(!/^\S+@gmail\.com$/i.test(email))return json({ok:false,error:"Valid Gmail address required"},400);if(password.length<8)return json({ok:false,error:"Password must be at least 8 characters"},400);if(await env.DB.prepare("SELECT id FROM auth_users WHERE lower(username)=lower(?) OR email=?").bind(username,email).first())return json({ok:false,error:"Username or Gmail already registered"},409);const id=crypto.randomUUID(),a=new Uint32Array(1);crypto.getRandomValues(a);const otp=String(100000+a[0]%900000);await env.DB.prepare("INSERT INTO auth_users(id,username,email,password_hash) VALUES(?,?,?,?)").bind(id,username,email,await phash(password)).run();await env.DB.prepare("INSERT INTO email_otps(id,user_id,otp_hash,expires_at) VALUES(?,?,?,datetime('now','+10 minutes'))").bind(crypto.randomUUID(),id,await hash(otp)).run();if(!await otpMail(env,email,otp)){await env.DB.prepare("DELETE FROM email_otps WHERE user_id=?").bind(id).run();await env.DB.prepare("DELETE FROM auth_users WHERE id=?").bind(id).run();return json({ok:false,error:"Email service is not configured"},503)}return json({ok:true,user_id:id,message:"OTP sent to your Gmail"})}
 if(url.pathname==="/api/verify-email"&&r.method==="POST"){const b=await r.json().catch(()=>({})),id=String(b.user_id||""),otp=String(b.otp||""),x=await env.DB.prepare("SELECT * FROM email_otps WHERE user_id=? ORDER BY created_at DESC LIMIT 1").bind(id).first();if(!x||x.attempts>=5||new Date(String(x.expires_at).replace(" ","T")+"Z")<new Date())return json({ok:false,error:"OTP expired"},400);if(await hash(otp)!==x.otp_hash){await env.DB.prepare("UPDATE email_otps SET attempts=attempts+1 WHERE id=?").bind(x.id).run();return json({ok:false,error:"Invalid OTP"},400)}await env.DB.prepare("UPDATE auth_users SET email_verified=1 WHERE id=?").bind(id).run();await env.DB.prepare("DELETE FROM email_otps WHERE user_id=?").bind(id).run();return json({ok:true,message:"Gmail verified. Login now."})}
 if(url.pathname==="/api/login"&&r.method==="POST"){const b=await r.json().catch(()=>({})),i=String(b.username||b.email||"").trim().toLowerCase(),p=String(b.password||""),u=await env.DB.prepare("SELECT * FROM auth_users WHERE lower(username)=? OR lower(email)=?").bind(i,i).first();if(!u||!(await pverify(p,u.password_hash)))return json({ok:false,error:"Invalid username/email or password"},401);if(!u.email_verified)return json({ok:false,error:"Verify Gmail OTP first"},403);const token=crypto.randomUUID()+crypto.randomUUID();await env.DB.prepare("DELETE FROM sessions WHERE user_id=?").bind(u.id).run();await env.DB.prepare("INSERT INTO sessions(id,user_id,token_hash,expires_at) VALUES(?,?,?,datetime('now','+30 days'))").bind(crypto.randomUUID(),u.id,await hash(token)).run();return new Response(JSON.stringify({ok:true,user:{id:u.id,username:u.username,email:u.email,display_name:u.display_name||u.username}}),{headers:{"Content-Type":"application/json","Set-Cookie":cookie("sc_session",token,2592000)}})}
 const u=await me(r,env.DB);if(!u)return json({ok:false,error:"Login required"},401);
 if(url.pathname==="/api/me")return json({ok:true,user:u});
 if(url.pathname==="/api/logout"&&r.method==="POST"){await env.DB.prepare("DELETE FROM sessions WHERE user_id=?").bind(u.id).run();return new Response(JSON.stringify({ok:true}),{headers:{"Content-Type":"application/json","Set-Cookie":cookie("sc_session","",0)}})}
 if(url.pathname==="/api/users/search"&&r.method==="GET"){const q=(url.searchParams.get("q")||"").trim();const {results}=await env.DB.prepare("SELECT id,username,display_name FROM auth_users WHERE email_verified=1 AND id!=? AND lower(username) LIKE ? LIMIT 20").bind(u.id,`%${q.toLowerCase()}%`).all();return json({ok:true,users:results||[]})}
 if(url.pathname==="/api/friends/request"&&r.method==="POST"){const b=await r.json().catch(()=>({})),name=String(b.username||"").trim(),v=await env.DB.prepare("SELECT id,username FROM auth_users WHERE lower(username)=lower(?) AND email_verified=1").bind(name).first();if(!v||v.id===u.id)return json({ok:false,error:"User not found"},404);if(await friendship(env.DB,u.id,v.id))return json({ok:false,error:"Already friends"},409);if(await env.DB.prepare("SELECT id FROM friend_requests WHERE sender_id=? AND receiver_id=? AND status='pending'").bind(u.id,v.id).first())return json({ok:false,error:"Request already sent"},409);const reverse=await env.DB.prepare("SELECT id FROM friend_requests WHERE sender_id=? AND receiver_id=? AND status='pending'").bind(v.id,u.id).first();if(reverse)return json({ok:false,error:"This user already sent you a request"},409);await env.DB.prepare("INSERT INTO friend_requests(id,sender_id,receiver_id) VALUES(?,?,?)").bind(crypto.randomUUID(),u.id,v.id).run();return json({ok:true,message:"Friend request sent"})}
 if(url.pathname==="/api/friends/incoming"&&r.method==="GET"){const {results}=await env.DB.prepare("SELECT fr.id,u.username FROM friend_requests fr JOIN auth_users u ON u.id=fr.sender_id WHERE fr.receiver_id=? AND fr.status='pending' ORDER BY fr.created_at DESC").bind(u.id).all();return json({ok:true,requests:results||[]})}
 if(url.pathname==="/api/friends/respond"&&r.method==="POST"){const b=await r.json().catch(()=>({})),id=String(b.request_id||""),action=String(b.action||""),fr=await env.DB.prepare("SELECT * FROM friend_requests WHERE id=? AND receiver_id=? AND status='pending'").bind(id,u.id).first();if(!fr)return json({ok:false,error:"Request not found"},404);if(action==="decline"){await env.DB.prepare("UPDATE friend_requests SET status='declined' WHERE id=?").bind(id).run();return json({ok:true})}if(action!=="accept")return json({ok:false,error:"Invalid action"},400);const p=pair(fr.sender_id,fr.receiver_id);await env.DB.batch([env.DB.prepare("UPDATE friend_requests SET status='accepted' WHERE id=?").bind(id),env.DB.prepare("INSERT OR IGNORE INTO friendships(id,user1_id,user2_id) VALUES(?,?,?)").bind(crypto.randomUUID(),...p)]);return json({ok:true,message:"Friend request accepted"})}
 if(url.pathname==="/api/friends"&&r.method==="GET"){const {results}=await env.DB.prepare("SELECT u.id user_id,u.username,u.display_name FROM friendships f JOIN auth_users u ON u.id=CASE WHEN f.user1_id=? THEN f.user2_id ELSE f.user1_id END WHERE f.user1_id=? OR f.user2_id=? ORDER BY u.username").bind(u.id,u.id,u.id).all();return json({ok:true,friends:results||[]})}
 if(url.pathname==="/api/chat/keys"&&r.method==="POST"){const b=await r.json().catch(()=>({})),key=String(b.public_key||"");if(key.length<20||key.length>5000)return json({ok:false,error:"Invalid public key"},400);await env.DB.prepare("INSERT INTO chat_keys(user_id,public_key) VALUES(?,?) ON CONFLICT(user_id) DO UPDATE SET public_key=excluded.public_key,updated_at=CURRENT_TIMESTAMP").bind(u.id,key).run();return json({ok:true})}
 if(url.pathname==="/api/chat/keys"&&r.method==="GET"){const {results}=await env.DB.prepare("SELECT ck.user_id,ck.public_key FROM chat_keys ck JOIN friendships f ON (f.user1_id=? AND f.user2_id=ck.user_id) OR (f.user2_id=? AND f.user1_id=ck.user_id)").bind(u.id,u.id).all();return json({ok:true,keys:results||[]})}
 if(url.pathname==="/api/posts"&&r.method==="GET"){const {results}=await env.DB.prepare("SELECT id,user_id,username,content,created_at FROM app_posts ORDER BY created_at DESC LIMIT 100").all();return json({ok:true,posts:results||[]})}
 if(url.pathname==="/api/posts"&&r.method==="POST"){const b=await r.json().catch(()=>({})),c=String(b.content||"").trim();if(!c)return json({ok:false,error:"Post is empty"},400);if(c.length>2000)return json({ok:false,error:"Maximum 2000 characters"},400);await env.DB.prepare("INSERT INTO app_posts(id,user_id,username,content) VALUES(?,?,?,?)").bind(crypto.randomUUID(),u.id,u.username,c).run();return json({ok:true})}
 return json({ok:false,error:"API route not found"},404);
}};
